spring:
  application:
    name: courses-crud
  datasource:
    username: hagwonschool
    hikari:
      maximum-pool-size: '5'
      connection-timeout: '20000'
    url: jdbc:postgresql://localhost:5431/courses
    password: '9607'
server:
  servlet:
    context-path: /courses-crud
  port: '8081'
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
eureka:
  instance:
    instance-id: "${spring.application-name}:${random.value}"
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/